name: Spell

on:
  pull_request:
    paths:
      - "nxdrive/data/i18n.json"
      - "**/*.md"
      - "**/*.py"
      - "**/*.sh"
      - ".github/workflows/spell.yml"

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # XXX_PYTHON
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements-tests.txt', 'tools/deps/requirements-tox.txt') }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements-tests.txt', 'tools/deps/requirements-tox.txt') }}
      - uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements-tests.txt', 'tools/deps/requirements-tox.txt') }}
          restore-keys: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements-tests.txt', 'tools/deps/requirements-tox.txt') }}
      - name: Install dependencies
        run: python -m pip install -r tools/deps/requirements-tox.txt
      - name: Spell check
        run: tox -e spell
